### ISSUE TITLE
Inconsistency between `EncoderWriter` and `DecoderReader` with 0.13

### ISSUE THREAD

**Issue by Blub** [marshallpierce/rust-base64#151]
I had wrappers for decoders and encoders they can own their respective reader or writer and saw that 0.13 already changed this for encoders, but not for decoders. I was wondering if this is intentional, or could be changed for >=0.14?

**Comment by marshallpierce** [comment]
`EncoderWriter` owns its delegate `Write` because as I was adding `EncoderStringWriter` I realized that `Write` is [implemented](https://doc.rust-lang.org/src/std/io/impls.rs.html#52-82) for `&mut Write`. `Read` has the [same thing](https://doc.rust-lang.org/src/std/io/impls.rs.html#15-50) in place, but I didn't think to apply the corresponding improvement in `DecoderReader`. So no, it wasn't intentional -- just an oversight. I don't see any reason to not also put it in place for decoding in the next release.
