### ISSUE TITLE
add plantuml character set

### ISSUE THREAD

**Issue by danieleades** [marshallpierce/rust-base64#174]
Plantuml uses a non-standard character set. It would be handy if this was supported.

see https://plantuml.com/text-encoding

**Comment by danieleades** [comment]
scratch that, i see you define a custom alphabet in `0.2.X-alpha`. Do you know when that's likely to be stabilised?

**Comment by marshallpierce** [comment]
The 0.2 alpha is only an alpha because I wanted to get the engine, etc, stuff out there for interested parties to use and provide feedback on the API in a way that didn't require extra work in your Cargo.toml. I do not expect any stability or correctness problems, and I would feel comfortable using it in production code if you're OK with the fact that the API might change a little by 0.20 if people find issues. So, go ahead and adopt it and enjoy your custom character set if that tradeoff is okay for you. The non-alpha release of 0.20 will happen when I have time to incorporate https://github.com/marshallpierce/rust-base64/pull/170. Once that's had some time for people to provide further feedback, it will likely become 1.0.

**Comment by marshallpierce** [comment]
This is available in 0.20.0+ now.
