### ISSUE TITLE
Successfully decode invalid input

### ISSUE THREAD

**Issue by hansonchar** [marshallpierce/rust-base64#189]
"djAuMC4x" is a valid base-64 encoded string whereas "djAuMC4" is not.

However, the latest v0.13.0 decodes both strings successfully when decoding the invalid one should fail.

**Comment by marshallpierce** [comment]
Thanks for the report; I'll look into it.

**Comment by marshallpierce** [comment]
This is related to https://github.com/marshallpierce/rust-base64/issues/182. Since padding doesn't perform any useful function, the decode logic does not currently require it.

I have some in-progress work to make padding required by default (but configurable to require no padding, or be indifferent).

**Comment by marshallpierce** [comment]
Give #198 a try and see if the error reporting works for your use case.

**Comment by hansonchar** [comment]
Great, it works!

**Comment by marshallpierce** [comment]
Released in 0.20.0.
