### ISSUE TITLE
Calling `EncoderStringWriter::write` successively does not equal `EncoderStringWriter::write_all`

### ISSUE THREAD

**Issue by nascent-harry** [marshallpierce/rust-base64#247]
# The problem

From the docs it seems like using `EncoderStringWriter::write` incrementally and `EncoderStringWriter::write_all` once should produce the same result.

This is not the case as seen in the following example:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=5ec7ce07f0bd526e7cb8272134eff351

**Comment by marshallpierce** [comment]
Hm, that doesn't seem great. Thanks for the report; I'll look into it.

**Comment by marshallpierce** [comment]
The issue is that the third write() call isn't consuming all of the input, which is per the spec. It only consumes the first two bytes. If you call write() again with the remaining un-used input, all is well: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a0770eb15be84f64778143d78e8b500a. I'll also add a test to _ensure_ this works.
